on:
    push:
      tags:
        - 'v*'
  
name: Create RPM Release

jobs:
    build:
        name: Create RPM Release
        runs-on: ubuntu-latest

        steps:

        - name: Checkout code
          uses: actions/checkout@master

        - name: build RPM package
          id: rpm_build
          uses: AnjaloHettiarachchi/rpmbuild@v1.0.0
          with:
              spec_file: "spec_for_yml_config/etcd.spec"

        - name: Create Release
          id: create_release
          uses: actions/create-release@latest
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              tag_name: ${{ github.ref }}
              release_name: Release ${{ github.ref }}
              body: |
                Changes in this Release
                - Create RPM
                - Upload Source RPM
              draft: false
              prerelease: false
            
        - name: Upload RPM as a release asset
          id: upload_rpm_release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ steps.rpm_build.outputs.rpm_path }}
            asset_name: ${{ steps.rpm_build.outputs.rpm_name }}
            asset_content_type: ${{ steps.rpm_build.outputs.content_type }}

        - name: Upload SRPM as a release asset
          id: upload_srpm_release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ steps.rpm_build.outputs.srpm_path }}
            asset_name: ${{ steps.rpm_build.outputs.srpm_name }}
            asset_content_type: ${{ steps.rpm_build.outputs.content_type }}